// Generated by gencpp from file vision_msgs/CubesSegmented.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_CUBESSEGMENTED_H
#define VISION_MSGS_MESSAGE_CUBESSEGMENTED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vision_msgs/Cube.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct CubesSegmented_
{
  typedef CubesSegmented_<ContainerAllocator> Type;

  CubesSegmented_()
    : header()
    , recog_cubes()  {
    }
  CubesSegmented_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , recog_cubes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vision_msgs::Cube_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vision_msgs::Cube_<ContainerAllocator> >::other >  _recog_cubes_type;
  _recog_cubes_type recog_cubes;





  typedef boost::shared_ptr< ::vision_msgs::CubesSegmented_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::CubesSegmented_<ContainerAllocator> const> ConstPtr;

}; // struct CubesSegmented_

typedef ::vision_msgs::CubesSegmented_<std::allocator<void> > CubesSegmented;

typedef boost::shared_ptr< ::vision_msgs::CubesSegmented > CubesSegmentedPtr;
typedef boost::shared_ptr< ::vision_msgs::CubesSegmented const> CubesSegmentedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::CubesSegmented_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::CubesSegmented_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::CubesSegmented_<ContainerAllocator1> & lhs, const ::vision_msgs::CubesSegmented_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.recog_cubes == rhs.recog_cubes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::CubesSegmented_<ContainerAllocator1> & lhs, const ::vision_msgs::CubesSegmented_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::CubesSegmented_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::CubesSegmented_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::CubesSegmented_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b935aade8f9275f5577fcbf7010f212";
  }

  static const char* value(const ::vision_msgs::CubesSegmented_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b935aade8f9275fULL;
  static const uint64_t static_value2 = 0x5577fcbf7010f212ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/CubesSegmented";
  }

  static const char* value(const ::vision_msgs::CubesSegmented_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"vision_msgs/Cube[] recog_cubes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/Cube\n"
"string color #color of the cube\n"
"geometry_msgs/Point cube_centroid		#Cube Centroid (x,y,z)\n"
"bool detected_cube    #flag to indicate if the cube was detected\n"
"geometry_msgs/Point minPoint	#Cube's min point\n"
"geometry_msgs/Point maxPoint	#Cube's max point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vision_msgs::CubesSegmented_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.recog_cubes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubesSegmented_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::CubesSegmented_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::CubesSegmented_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "recog_cubes[]" << std::endl;
    for (size_t i = 0; i < v.recog_cubes.size(); ++i)
    {
      s << indent << "  recog_cubes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vision_msgs::Cube_<ContainerAllocator> >::stream(s, indent + "    ", v.recog_cubes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_CUBESSEGMENTED_H
