// Generated by gencpp from file vision_msgs/DetectObjectsInPlaneRequest.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_DETECTOBJECTSINPLANEREQUEST_H
#define VISION_MSGS_MESSAGE_DETECTOBJECTSINPLANEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct DetectObjectsInPlaneRequest_
{
  typedef DetectObjectsInPlaneRequest_<ContainerAllocator> Type;

  DetectObjectsInPlaneRequest_()
    : plane_height()  {
    }
  DetectObjectsInPlaneRequest_(const ContainerAllocator& _alloc)
    : plane_height(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _plane_height_type;
  _plane_height_type plane_height;





  typedef boost::shared_ptr< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectsInPlaneRequest_

typedef ::vision_msgs::DetectObjectsInPlaneRequest_<std::allocator<void> > DetectObjectsInPlaneRequest;

typedef boost::shared_ptr< ::vision_msgs::DetectObjectsInPlaneRequest > DetectObjectsInPlaneRequestPtr;
typedef boost::shared_ptr< ::vision_msgs::DetectObjectsInPlaneRequest const> DetectObjectsInPlaneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator1> & lhs, const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plane_height == rhs.plane_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator1> & lhs, const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0ad85afd6a25f78ecdd5a1ea7003a88";
  }

  static const char* value(const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0ad85afd6a25f78ULL;
  static const uint64_t static_value2 = 0xecdd5a1ea7003a88ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/DetectObjectsInPlaneRequest";
  }

  static const char* value(const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 plane_height\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plane_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectObjectsInPlaneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::DetectObjectsInPlaneRequest_<ContainerAllocator>& v)
  {
    s << indent << "plane_height: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.plane_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_DETECTOBJECTSINPLANEREQUEST_H
