// Generated by gencpp from file vision_msgs/FaceRecognitionRequest.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_FACERECOGNITIONREQUEST_H
#define VISION_MSGS_MESSAGE_FACERECOGNITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <vision_msgs/VisionFaceObjects.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct FaceRecognitionRequest_
{
  typedef FaceRecognitionRequest_<ContainerAllocator> Type;

  FaceRecognitionRequest_()
    : id()
    , enable_age_gender(false)
    , imageBGR()
    , faces()  {
    }
  FaceRecognitionRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , enable_age_gender(false)
    , imageBGR(_alloc)
    , faces(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef uint8_t _enable_age_gender_type;
  _enable_age_gender_type enable_age_gender;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _imageBGR_type;
  _imageBGR_type imageBGR;

   typedef  ::vision_msgs::VisionFaceObjects_<ContainerAllocator>  _faces_type;
  _faces_type faces;





  typedef boost::shared_ptr< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceRecognitionRequest_

typedef ::vision_msgs::FaceRecognitionRequest_<std::allocator<void> > FaceRecognitionRequest;

typedef boost::shared_ptr< ::vision_msgs::FaceRecognitionRequest > FaceRecognitionRequestPtr;
typedef boost::shared_ptr< ::vision_msgs::FaceRecognitionRequest const> FaceRecognitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator1> & lhs, const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.enable_age_gender == rhs.enable_age_gender &&
    lhs.imageBGR == rhs.imageBGR &&
    lhs.faces == rhs.faces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator1> & lhs, const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eab4f03bc6af4399806e3568f6be4af";
  }

  static const char* value(const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eab4f03bc6af439ULL;
  static const uint64_t static_value2 = 0x9806e3568f6be4afULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/FaceRecognitionRequest";
  }

  static const char* value(const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"bool enable_age_gender\n"
"sensor_msgs/Image imageBGR\n"
"vision_msgs/VisionFaceObjects faces\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/VisionFaceObjects\n"
"std_msgs/Header header\n"
"vision_msgs/VisionFaceObject[] recog_faces\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/VisionFaceObject\n"
"string id                                    #face id\n"
"float32 confidence                           #value in [0,1] indicating the probability of a correct identification\n"
"geometry_msgs/Point face_centroid            #Face Centroid (x,y,z)\n"
"geometry_msgs/Point[] bounding_box           #Face bounding box 2D\n"
"bool smile                                   #smiling face\n"
"int8 gender                                  #Gender ID. 0: female, 1: male, 2: unknown\n"
"int8 ages                             	     #Ages ID. 0: children, 1: adult, 2: elder\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.enable_age_gender);
      stream.next(m.imageBGR);
      stream.next(m.faces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceRecognitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::FaceRecognitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "enable_age_gender: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_age_gender);
    s << indent << "imageBGR: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.imageBGR);
    s << indent << "faces: ";
    s << std::endl;
    Printer< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >::stream(s, indent + "  ", v.faces);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_FACERECOGNITIONREQUEST_H
