// Generated by gencpp from file vision_msgs/FindPlaneAtHeightRequest.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_FINDPLANEATHEIGHTREQUEST_H
#define VISION_MSGS_MESSAGE_FINDPLANEATHEIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct FindPlaneAtHeightRequest_
{
  typedef FindPlaneAtHeightRequest_<ContainerAllocator> Type;

  FindPlaneAtHeightRequest_()
    : name()
    , point_cloud()
    , minH()
    , maxH()  {
    }
  FindPlaneAtHeightRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , point_cloud(_alloc)
    , minH(_alloc)
    , maxH(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _point_cloud_type;
  _point_cloud_type point_cloud;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _minH_type;
  _minH_type minH;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _maxH_type;
  _maxH_type maxH;





  typedef boost::shared_ptr< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindPlaneAtHeightRequest_

typedef ::vision_msgs::FindPlaneAtHeightRequest_<std::allocator<void> > FindPlaneAtHeightRequest;

typedef boost::shared_ptr< ::vision_msgs::FindPlaneAtHeightRequest > FindPlaneAtHeightRequestPtr;
typedef boost::shared_ptr< ::vision_msgs::FindPlaneAtHeightRequest const> FindPlaneAtHeightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator1> & lhs, const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.point_cloud == rhs.point_cloud &&
    lhs.minH == rhs.minH &&
    lhs.maxH == rhs.maxH;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator1> & lhs, const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38321a2d569f0a3167c20ac0dd0049c3";
  }

  static const char* value(const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38321a2d569f0a31ULL;
  static const uint64_t static_value2 = 0x67c20ac0dd0049c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/FindPlaneAtHeightRequest";
  }

  static const char* value(const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"sensor_msgs/PointCloud2 point_cloud\n"
"std_msgs/Float64  minH\n"
"std_msgs/Float64 maxH\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.point_cloud);
      stream.next(m.minH);
      stream.next(m.maxH);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindPlaneAtHeightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::FindPlaneAtHeightRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "point_cloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.point_cloud);
    s << indent << "minH: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.minH);
    s << indent << "maxH: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.maxH);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_FINDPLANEATHEIGHTREQUEST_H
