// Generated by gencpp from file vision_msgs/FindWavingRequest.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_FINDWAVINGREQUEST_H
#define VISION_MSGS_MESSAGE_FINDWAVINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct FindWavingRequest_
{
  typedef FindWavingRequest_<ContainerAllocator> Type;

  FindWavingRequest_()
    {
    }
  FindWavingRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vision_msgs::FindWavingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::FindWavingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindWavingRequest_

typedef ::vision_msgs::FindWavingRequest_<std::allocator<void> > FindWavingRequest;

typedef boost::shared_ptr< ::vision_msgs::FindWavingRequest > FindWavingRequestPtr;
typedef boost::shared_ptr< ::vision_msgs::FindWavingRequest const> FindWavingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::FindWavingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::FindWavingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::FindWavingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::FindWavingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vision_msgs::FindWavingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/FindWavingRequest";
  }

  static const char* value(const ::vision_msgs::FindWavingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vision_msgs::FindWavingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindWavingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::FindWavingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vision_msgs::FindWavingRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_FINDWAVINGREQUEST_H
