// Generated by gencpp from file vision_msgs/GetCubesResponse.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_GETCUBESRESPONSE_H
#define VISION_MSGS_MESSAGE_GETCUBESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision_msgs/CubesSegmented.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct GetCubesResponse_
{
  typedef GetCubesResponse_<ContainerAllocator> Type;

  GetCubesResponse_()
    : cubes_output()  {
    }
  GetCubesResponse_(const ContainerAllocator& _alloc)
    : cubes_output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vision_msgs::CubesSegmented_<ContainerAllocator>  _cubes_output_type;
  _cubes_output_type cubes_output;





  typedef boost::shared_ptr< ::vision_msgs::GetCubesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::GetCubesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCubesResponse_

typedef ::vision_msgs::GetCubesResponse_<std::allocator<void> > GetCubesResponse;

typedef boost::shared_ptr< ::vision_msgs::GetCubesResponse > GetCubesResponsePtr;
typedef boost::shared_ptr< ::vision_msgs::GetCubesResponse const> GetCubesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::GetCubesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::GetCubesResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::GetCubesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cubes_output == rhs.cubes_output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::GetCubesResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::GetCubesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::GetCubesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::GetCubesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::GetCubesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be6b91864d949081c0a4e00a949d7867";
  }

  static const char* value(const ::vision_msgs::GetCubesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe6b91864d949081ULL;
  static const uint64_t static_value2 = 0xc0a4e00a949d7867ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/GetCubesResponse";
  }

  static const char* value(const ::vision_msgs::GetCubesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/CubesSegmented cubes_output\n"
"\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/CubesSegmented\n"
"std_msgs/Header header\n"
"vision_msgs/Cube[] recog_cubes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/Cube\n"
"string color #color of the cube\n"
"geometry_msgs/Point cube_centroid		#Cube Centroid (x,y,z)\n"
"bool detected_cube    #flag to indicate if the cube was detected\n"
"geometry_msgs/Point minPoint	#Cube's min point\n"
"geometry_msgs/Point maxPoint	#Cube's max point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vision_msgs::GetCubesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cubes_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCubesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::GetCubesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::GetCubesResponse_<ContainerAllocator>& v)
  {
    s << indent << "cubes_output: ";
    s << std::endl;
    Printer< ::vision_msgs::CubesSegmented_<ContainerAllocator> >::stream(s, indent + "  ", v.cubes_output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_GETCUBESRESPONSE_H
