// Generated by gencpp from file vision_msgs/HandCameraGraspResponse.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_HANDCAMERAGRASPRESPONSE_H
#define VISION_MSGS_MESSAGE_HANDCAMERAGRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct HandCameraGraspResponse_
{
  typedef HandCameraGraspResponse_<ContainerAllocator> Type;

  HandCameraGraspResponse_()
    : finish(false)  {
    }
  HandCameraGraspResponse_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HandCameraGraspResponse_

typedef ::vision_msgs::HandCameraGraspResponse_<std::allocator<void> > HandCameraGraspResponse;

typedef boost::shared_ptr< ::vision_msgs::HandCameraGraspResponse > HandCameraGraspResponsePtr;
typedef boost::shared_ptr< ::vision_msgs::HandCameraGraspResponse const> HandCameraGraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/HandCameraGraspResponse";
  }

  static const char* value(const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finish\n"
"\n"
;
  }

  static const char* value(const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandCameraGraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::HandCameraGraspResponse_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_HANDCAMERAGRASPRESPONSE_H
