// Generated by gencpp from file vision_msgs/OpenPoseKeyPoint.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_OPENPOSEKEYPOINT_H
#define VISION_MSGS_MESSAGE_OPENPOSEKEYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_msgs
{
template <class ContainerAllocator>
struct OpenPoseKeyPoint_
{
  typedef OpenPoseKeyPoint_<ContainerAllocator> Type;

  OpenPoseKeyPoint_()
    : x(0)
    , y(0)
    , score(0.0)  {
    }
  OpenPoseKeyPoint_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , score(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef float _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> const> ConstPtr;

}; // struct OpenPoseKeyPoint_

typedef ::vision_msgs::OpenPoseKeyPoint_<std::allocator<void> > OpenPoseKeyPoint;

typedef boost::shared_ptr< ::vision_msgs::OpenPoseKeyPoint > OpenPoseKeyPointPtr;
typedef boost::shared_ptr< ::vision_msgs::OpenPoseKeyPoint const> OpenPoseKeyPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator1> & lhs, const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator1> & lhs, const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04b19d5038aa7917ea506d131722e276";
  }

  static const char* value(const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04b19d5038aa7917ULL;
  static const uint64_t static_value2 = 0xea506d131722e276ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/OpenPoseKeyPoint";
  }

  static const char* value(const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n"
"int16 y\n"
"float32 score\n"
;
  }

  static const char* value(const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenPoseKeyPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::OpenPoseKeyPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_OPENPOSEKEYPOINT_H
