// Generated by gencpp from file vision_msgs/OpenPoseRecognize.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_OPENPOSERECOGNIZE_H
#define VISION_MSGS_MESSAGE_OPENPOSERECOGNIZE_H

#include <ros/service_traits.h>


#include <vision_msgs/OpenPoseRecognizeRequest.h>
#include <vision_msgs/OpenPoseRecognizeResponse.h>


namespace vision_msgs
{

struct OpenPoseRecognize
{

typedef OpenPoseRecognizeRequest Request;
typedef OpenPoseRecognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OpenPoseRecognize
} // namespace vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_msgs::OpenPoseRecognize > {
  static const char* value()
  {
    return "bc6fe00995db36c68d2577234a53f272";
  }

  static const char* value(const ::vision_msgs::OpenPoseRecognize&) { return value(); }
};

template<>
struct DataType< ::vision_msgs::OpenPoseRecognize > {
  static const char* value()
  {
    return "vision_msgs/OpenPoseRecognize";
  }

  static const char* value(const ::vision_msgs::OpenPoseRecognize&) { return value(); }
};


// service_traits::MD5Sum< ::vision_msgs::OpenPoseRecognizeRequest> should match
// service_traits::MD5Sum< ::vision_msgs::OpenPoseRecognize >
template<>
struct MD5Sum< ::vision_msgs::OpenPoseRecognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_msgs::OpenPoseRecognize >::value();
  }
  static const char* value(const ::vision_msgs::OpenPoseRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_msgs::OpenPoseRecognizeRequest> should match
// service_traits::DataType< ::vision_msgs::OpenPoseRecognize >
template<>
struct DataType< ::vision_msgs::OpenPoseRecognizeRequest>
{
  static const char* value()
  {
    return DataType< ::vision_msgs::OpenPoseRecognize >::value();
  }
  static const char* value(const ::vision_msgs::OpenPoseRecognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_msgs::OpenPoseRecognizeResponse> should match
// service_traits::MD5Sum< ::vision_msgs::OpenPoseRecognize >
template<>
struct MD5Sum< ::vision_msgs::OpenPoseRecognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_msgs::OpenPoseRecognize >::value();
  }
  static const char* value(const ::vision_msgs::OpenPoseRecognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_msgs::OpenPoseRecognizeResponse> should match
// service_traits::DataType< ::vision_msgs::OpenPoseRecognize >
template<>
struct DataType< ::vision_msgs::OpenPoseRecognizeResponse>
{
  static const char* value()
  {
    return DataType< ::vision_msgs::OpenPoseRecognize >::value();
  }
  static const char* value(const ::vision_msgs::OpenPoseRecognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MSGS_MESSAGE_OPENPOSERECOGNIZE_H
