// Generated by gencpp from file vision_msgs/OpenPoseRecognizeResponse.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_OPENPOSERECOGNIZERESPONSE_H
#define VISION_MSGS_MESSAGE_OPENPOSERECOGNIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision_msgs/OpenPoseRecognition.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct OpenPoseRecognizeResponse_
{
  typedef OpenPoseRecognizeResponse_<ContainerAllocator> Type;

  OpenPoseRecognizeResponse_()
    : recognitions()  {
    }
  OpenPoseRecognizeResponse_(const ContainerAllocator& _alloc)
    : recognitions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::vision_msgs::OpenPoseRecognition_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vision_msgs::OpenPoseRecognition_<ContainerAllocator> >::other >  _recognitions_type;
  _recognitions_type recognitions;





  typedef boost::shared_ptr< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OpenPoseRecognizeResponse_

typedef ::vision_msgs::OpenPoseRecognizeResponse_<std::allocator<void> > OpenPoseRecognizeResponse;

typedef boost::shared_ptr< ::vision_msgs::OpenPoseRecognizeResponse > OpenPoseRecognizeResponsePtr;
typedef boost::shared_ptr< ::vision_msgs::OpenPoseRecognizeResponse const> OpenPoseRecognizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.recognitions == rhs.recognitions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator1> & lhs, const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "948e770d3707769324b3f1f72c6c76bf";
  }

  static const char* value(const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x948e770d37077693ULL;
  static const uint64_t static_value2 = 0x24b3f1f72c6c76bfULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/OpenPoseRecognizeResponse";
  }

  static const char* value(const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/OpenPoseRecognition[] recognitions\n"
"\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/OpenPoseRecognition\n"
"vision_msgs/OpenPoseKeyPoint[] keyPoints\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/OpenPoseKeyPoint\n"
"int16 x\n"
"int16 y\n"
"float32 score\n"
;
  }

  static const char* value(const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recognitions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenPoseRecognizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::OpenPoseRecognizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "recognitions[]" << std::endl;
    for (size_t i = 0; i < v.recognitions.size(); ++i)
    {
      s << indent << "  recognitions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vision_msgs::OpenPoseRecognition_<ContainerAllocator> >::stream(s, indent + "    ", v.recognitions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_OPENPOSERECOGNIZERESPONSE_H
