// Generated by gencpp from file vision_msgs/SRV_DetectPlasticTrayZones.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_SRV_DETECTPLASTICTRAYZONES_H
#define VISION_MSGS_MESSAGE_SRV_DETECTPLASTICTRAYZONES_H

#include <ros/service_traits.h>


#include <vision_msgs/SRV_DetectPlasticTrayZonesRequest.h>
#include <vision_msgs/SRV_DetectPlasticTrayZonesResponse.h>


namespace vision_msgs
{

struct SRV_DetectPlasticTrayZones
{

typedef SRV_DetectPlasticTrayZonesRequest Request;
typedef SRV_DetectPlasticTrayZonesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SRV_DetectPlasticTrayZones
} // namespace vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZones > {
  static const char* value()
  {
    return "10ac3c12f5e606b8bd3e61c34f4feba3";
  }

  static const char* value(const ::vision_msgs::SRV_DetectPlasticTrayZones&) { return value(); }
};

template<>
struct DataType< ::vision_msgs::SRV_DetectPlasticTrayZones > {
  static const char* value()
  {
    return "vision_msgs/SRV_DetectPlasticTrayZones";
  }

  static const char* value(const ::vision_msgs::SRV_DetectPlasticTrayZones&) { return value(); }
};


// service_traits::MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZonesRequest> should match
// service_traits::MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZones >
template<>
struct MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZonesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZones >::value();
  }
  static const char* value(const ::vision_msgs::SRV_DetectPlasticTrayZonesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_msgs::SRV_DetectPlasticTrayZonesRequest> should match
// service_traits::DataType< ::vision_msgs::SRV_DetectPlasticTrayZones >
template<>
struct DataType< ::vision_msgs::SRV_DetectPlasticTrayZonesRequest>
{
  static const char* value()
  {
    return DataType< ::vision_msgs::SRV_DetectPlasticTrayZones >::value();
  }
  static const char* value(const ::vision_msgs::SRV_DetectPlasticTrayZonesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZonesResponse> should match
// service_traits::MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZones >
template<>
struct MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZonesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision_msgs::SRV_DetectPlasticTrayZones >::value();
  }
  static const char* value(const ::vision_msgs::SRV_DetectPlasticTrayZonesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision_msgs::SRV_DetectPlasticTrayZonesResponse> should match
// service_traits::DataType< ::vision_msgs::SRV_DetectPlasticTrayZones >
template<>
struct DataType< ::vision_msgs::SRV_DetectPlasticTrayZonesResponse>
{
  static const char* value()
  {
    return DataType< ::vision_msgs::SRV_DetectPlasticTrayZones >::value();
  }
  static const char* value(const ::vision_msgs::SRV_DetectPlasticTrayZonesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MSGS_MESSAGE_SRV_DETECTPLASTICTRAYZONES_H
