// Generated by gencpp from file vision_msgs/VisionFaceObjects.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_VISIONFACEOBJECTS_H
#define VISION_MSGS_MESSAGE_VISIONFACEOBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vision_msgs/VisionFaceObject.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct VisionFaceObjects_
{
  typedef VisionFaceObjects_<ContainerAllocator> Type;

  VisionFaceObjects_()
    : header()
    , recog_faces()  {
    }
  VisionFaceObjects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , recog_faces(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vision_msgs::VisionFaceObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vision_msgs::VisionFaceObject_<ContainerAllocator> >::other >  _recog_faces_type;
  _recog_faces_type recog_faces;





  typedef boost::shared_ptr< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> const> ConstPtr;

}; // struct VisionFaceObjects_

typedef ::vision_msgs::VisionFaceObjects_<std::allocator<void> > VisionFaceObjects;

typedef boost::shared_ptr< ::vision_msgs::VisionFaceObjects > VisionFaceObjectsPtr;
typedef boost::shared_ptr< ::vision_msgs::VisionFaceObjects const> VisionFaceObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::VisionFaceObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::VisionFaceObjects_<ContainerAllocator1> & lhs, const ::vision_msgs::VisionFaceObjects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.recog_faces == rhs.recog_faces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::VisionFaceObjects_<ContainerAllocator1> & lhs, const ::vision_msgs::VisionFaceObjects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b363d06da4711f3b7e8c1da373f69412";
  }

  static const char* value(const ::vision_msgs::VisionFaceObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb363d06da4711f3bULL;
  static const uint64_t static_value2 = 0x7e8c1da373f69412ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/VisionFaceObjects";
  }

  static const char* value(const ::vision_msgs::VisionFaceObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"vision_msgs/VisionFaceObject[] recog_faces\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/VisionFaceObject\n"
"string id                                    #face id\n"
"float32 confidence                           #value in [0,1] indicating the probability of a correct identification\n"
"geometry_msgs/Point face_centroid            #Face Centroid (x,y,z)\n"
"geometry_msgs/Point[] bounding_box           #Face bounding box 2D\n"
"bool smile                                   #smiling face\n"
"int8 gender                                  #Gender ID. 0: female, 1: male, 2: unknown\n"
"int8 ages                             	     #Ages ID. 0: children, 1: adult, 2: elder\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vision_msgs::VisionFaceObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.recog_faces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionFaceObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::VisionFaceObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::VisionFaceObjects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "recog_faces[]" << std::endl;
    for (size_t i = 0; i < v.recog_faces.size(); ++i)
    {
      s << indent << "  recog_faces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vision_msgs::VisionFaceObject_<ContainerAllocator> >::stream(s, indent + "    ", v.recog_faces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_VISIONFACEOBJECTS_H
