(cl:defpackage env_msgs-srv
  (:use )
  (:export
   "ADDUPDATEOBJECTVIZ"
   "<ADDUPDATEOBJECTVIZ-REQUEST>"
   "ADDUPDATEOBJECTVIZ-REQUEST"
   "<ADDUPDATEOBJECTVIZ-RESPONSE>"
   "ADDUPDATEOBJECTVIZ-RESPONSE"
  ))

