// Generated by gencpp from file env_msgs/AddUpdateObjectViz.msg
// DO NOT EDIT!


#ifndef ENV_MSGS_MESSAGE_ADDUPDATEOBJECTVIZ_H
#define ENV_MSGS_MESSAGE_ADDUPDATEOBJECTVIZ_H

#include <ros/service_traits.h>


#include <env_msgs/AddUpdateObjectVizRequest.h>
#include <env_msgs/AddUpdateObjectVizResponse.h>


namespace env_msgs
{

struct AddUpdateObjectViz
{

typedef AddUpdateObjectVizRequest Request;
typedef AddUpdateObjectVizResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddUpdateObjectViz
} // namespace env_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::env_msgs::AddUpdateObjectViz > {
  static const char* value()
  {
    return "0880db44a2d194fd7f70f843d3b298a2";
  }

  static const char* value(const ::env_msgs::AddUpdateObjectViz&) { return value(); }
};

template<>
struct DataType< ::env_msgs::AddUpdateObjectViz > {
  static const char* value()
  {
    return "env_msgs/AddUpdateObjectViz";
  }

  static const char* value(const ::env_msgs::AddUpdateObjectViz&) { return value(); }
};


// service_traits::MD5Sum< ::env_msgs::AddUpdateObjectVizRequest> should match
// service_traits::MD5Sum< ::env_msgs::AddUpdateObjectViz >
template<>
struct MD5Sum< ::env_msgs::AddUpdateObjectVizRequest>
{
  static const char* value()
  {
    return MD5Sum< ::env_msgs::AddUpdateObjectViz >::value();
  }
  static const char* value(const ::env_msgs::AddUpdateObjectVizRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::env_msgs::AddUpdateObjectVizRequest> should match
// service_traits::DataType< ::env_msgs::AddUpdateObjectViz >
template<>
struct DataType< ::env_msgs::AddUpdateObjectVizRequest>
{
  static const char* value()
  {
    return DataType< ::env_msgs::AddUpdateObjectViz >::value();
  }
  static const char* value(const ::env_msgs::AddUpdateObjectVizRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::env_msgs::AddUpdateObjectVizResponse> should match
// service_traits::MD5Sum< ::env_msgs::AddUpdateObjectViz >
template<>
struct MD5Sum< ::env_msgs::AddUpdateObjectVizResponse>
{
  static const char* value()
  {
    return MD5Sum< ::env_msgs::AddUpdateObjectViz >::value();
  }
  static const char* value(const ::env_msgs::AddUpdateObjectVizResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::env_msgs::AddUpdateObjectVizResponse> should match
// service_traits::DataType< ::env_msgs::AddUpdateObjectViz >
template<>
struct DataType< ::env_msgs::AddUpdateObjectVizResponse>
{
  static const char* value()
  {
    return DataType< ::env_msgs::AddUpdateObjectViz >::value();
  }
  static const char* value(const ::env_msgs::AddUpdateObjectVizResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENV_MSGS_MESSAGE_ADDUPDATEOBJECTVIZ_H
