// Generated by gencpp from file env_msgs/AddUpdateObjectVizResponse.msg
// DO NOT EDIT!


#ifndef ENV_MSGS_MESSAGE_ADDUPDATEOBJECTVIZRESPONSE_H
#define ENV_MSGS_MESSAGE_ADDUPDATEOBJECTVIZRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace env_msgs
{
template <class ContainerAllocator>
struct AddUpdateObjectVizResponse_
{
  typedef AddUpdateObjectVizResponse_<ContainerAllocator> Type;

  AddUpdateObjectVizResponse_()
    {
    }
  AddUpdateObjectVizResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddUpdateObjectVizResponse_

typedef ::env_msgs::AddUpdateObjectVizResponse_<std::allocator<void> > AddUpdateObjectVizResponse;

typedef boost::shared_ptr< ::env_msgs::AddUpdateObjectVizResponse > AddUpdateObjectVizResponsePtr;
typedef boost::shared_ptr< ::env_msgs::AddUpdateObjectVizResponse const> AddUpdateObjectVizResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace env_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "env_msgs/AddUpdateObjectVizResponse";
  }

  static const char* value(const ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddUpdateObjectVizResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::env_msgs::AddUpdateObjectVizResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ENV_MSGS_MESSAGE_ADDUPDATEOBJECTVIZRESPONSE_H
