// Generated by gencpp from file manip_msgs/InverseKinematicsPoseResponse.msg
// DO NOT EDIT!


#ifndef MANIP_MSGS_MESSAGE_INVERSEKINEMATICSPOSERESPONSE_H
#define MANIP_MSGS_MESSAGE_INVERSEKINEMATICSPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>

namespace manip_msgs
{
template <class ContainerAllocator>
struct InverseKinematicsPoseResponse_
{
  typedef InverseKinematicsPoseResponse_<ContainerAllocator> Type;

  InverseKinematicsPoseResponse_()
    : articular_pose()  {
    }
  InverseKinematicsPoseResponse_(const ContainerAllocator& _alloc)
    : articular_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _articular_pose_type;
  _articular_pose_type articular_pose;





  typedef boost::shared_ptr< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InverseKinematicsPoseResponse_

typedef ::manip_msgs::InverseKinematicsPoseResponse_<std::allocator<void> > InverseKinematicsPoseResponse;

typedef boost::shared_ptr< ::manip_msgs::InverseKinematicsPoseResponse > InverseKinematicsPoseResponsePtr;
typedef boost::shared_ptr< ::manip_msgs::InverseKinematicsPoseResponse const> InverseKinematicsPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator1> & lhs, const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.articular_pose == rhs.articular_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator1> & lhs, const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manip_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98280c273a083e97d905afcfe0befc9f";
  }

  static const char* value(const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98280c273a083e97ULL;
  static const uint64_t static_value2 = 0xd905afcfe0befc9fULL;
};

template<class ContainerAllocator>
struct DataType< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manip_msgs/InverseKinematicsPoseResponse";
  }

  static const char* value(const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray articular_pose     \n"
"\n"
"#Cartesian pose represents a position in a 6DOF space,\n"
"#neverthless, arm is 7DOF. The IK algorithm is supossed to calculate the best elbow position\n"
"#for the given cartesian pose.\n"
"\n"
"#Result is an array of seven floats representing the angular position for each motor in the arm\n"
"\n"
"#If goal pose is out of the workspace, a false should be returned when service is called.\n"
"#Reachability of a given position can be determined by trying to calculate its inverse kinematics\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.articular_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InverseKinematicsPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manip_msgs::InverseKinematicsPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "articular_pose: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.articular_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIP_MSGS_MESSAGE_INVERSEKINEMATICSPOSERESPONSE_H
