// Generated by gencpp from file moveit_services/moveitPositionResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_SERVICES_MESSAGE_MOVEITPOSITIONRESPONSE_H
#define MOVEIT_SERVICES_MESSAGE_MOVEITPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveit_services
{
template <class ContainerAllocator>
struct moveitPositionResponse_
{
  typedef moveitPositionResponse_<ContainerAllocator> Type;

  moveitPositionResponse_()
    : succes(false)  {
    }
  moveitPositionResponse_(const ContainerAllocator& _alloc)
    : succes(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succes_type;
  _succes_type succes;





  typedef boost::shared_ptr< ::moveit_services::moveitPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_services::moveitPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct moveitPositionResponse_

typedef ::moveit_services::moveitPositionResponse_<std::allocator<void> > moveitPositionResponse;

typedef boost::shared_ptr< ::moveit_services::moveitPositionResponse > moveitPositionResponsePtr;
typedef boost::shared_ptr< ::moveit_services::moveitPositionResponse const> moveitPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_services::moveitPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_services::moveitPositionResponse_<ContainerAllocator1> & lhs, const ::moveit_services::moveitPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.succes == rhs.succes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_services::moveitPositionResponse_<ContainerAllocator1> & lhs, const ::moveit_services::moveitPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_services::moveitPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_services::moveitPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_services::moveitPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "509793171e494962cd366ecf60e100e4";
  }

  static const char* value(const ::moveit_services::moveitPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x509793171e494962ULL;
  static const uint64_t static_value2 = 0xcd366ecf60e100e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_services/moveitPositionResponse";
  }

  static const char* value(const ::moveit_services::moveitPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool succes\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::moveit_services::moveitPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveitPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_services::moveitPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_services::moveitPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "succes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_SERVICES_MESSAGE_MOVEITPOSITIONRESPONSE_H
