// Generated by gencpp from file moveit_services/moveitPositionRequest.msg
// DO NOT EDIT!


#ifndef MOVEIT_SERVICES_MESSAGE_MOVEITPOSITIONREQUEST_H
#define MOVEIT_SERVICES_MESSAGE_MOVEITPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace moveit_services
{
template <class ContainerAllocator>
struct moveitPositionRequest_
{
  typedef moveitPositionRequest_<ContainerAllocator> Type;

  moveitPositionRequest_()
    : pose()
    , move_group()  {
    }
  moveitPositionRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , move_group(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _move_group_type;
  _move_group_type move_group;





  typedef boost::shared_ptr< ::moveit_services::moveitPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_services::moveitPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct moveitPositionRequest_

typedef ::moveit_services::moveitPositionRequest_<std::allocator<void> > moveitPositionRequest;

typedef boost::shared_ptr< ::moveit_services::moveitPositionRequest > moveitPositionRequestPtr;
typedef boost::shared_ptr< ::moveit_services::moveitPositionRequest const> moveitPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_services::moveitPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_services::moveitPositionRequest_<ContainerAllocator1> & lhs, const ::moveit_services::moveitPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.move_group == rhs.move_group;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_services::moveitPositionRequest_<ContainerAllocator1> & lhs, const ::moveit_services::moveitPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_services::moveitPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_services::moveitPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_services::moveitPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "517ade612bbc0fbff54fba1d4f4d4b76";
  }

  static const char* value(const ::moveit_services::moveitPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x517ade612bbc0fbfULL;
  static const uint64_t static_value2 = 0xf54fba1d4f4d4b76ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_services/moveitPositionRequest";
  }

  static const char* value(const ::moveit_services::moveitPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"string move_group\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::moveit_services::moveitPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.move_group);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveitPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_services::moveitPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_services::moveitPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "move_group: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.move_group);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_SERVICES_MESSAGE_MOVEITPOSITIONREQUEST_H
