// Generated by gencpp from file mvn_pln/mp_move_distResponse.msg
// DO NOT EDIT!


#ifndef MVN_PLN_MESSAGE_MP_MOVE_DISTRESPONSE_H
#define MVN_PLN_MESSAGE_MP_MOVE_DISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace mvn_pln
{
template <class ContainerAllocator>
struct mp_move_distResponse_
{
  typedef mp_move_distResponse_<ContainerAllocator> Type;

  mp_move_distResponse_()
    : traveledDistance()  {
    }
  mp_move_distResponse_(const ContainerAllocator& _alloc)
    : traveledDistance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _traveledDistance_type;
  _traveledDistance_type traveledDistance;





  typedef boost::shared_ptr< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mp_move_distResponse_

typedef ::mvn_pln::mp_move_distResponse_<std::allocator<void> > mp_move_distResponse;

typedef boost::shared_ptr< ::mvn_pln::mp_move_distResponse > mp_move_distResponsePtr;
typedef boost::shared_ptr< ::mvn_pln::mp_move_distResponse const> mp_move_distResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvn_pln::mp_move_distResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvn_pln::mp_move_distResponse_<ContainerAllocator1> & lhs, const ::mvn_pln::mp_move_distResponse_<ContainerAllocator2> & rhs)
{
  return lhs.traveledDistance == rhs.traveledDistance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvn_pln::mp_move_distResponse_<ContainerAllocator1> & lhs, const ::mvn_pln::mp_move_distResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvn_pln

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b4962461942d22bd56adac85e70348d";
  }

  static const char* value(const ::mvn_pln::mp_move_distResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b4962461942d22bULL;
  static const uint64_t static_value2 = 0xd56adac85e70348dULL;
};

template<class ContainerAllocator>
struct DataType< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvn_pln/mp_move_distResponse";
  }

  static const char* value(const ::mvn_pln::mp_move_distResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 traveledDistance\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::mvn_pln::mp_move_distResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traveledDistance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mp_move_distResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvn_pln::mp_move_distResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvn_pln::mp_move_distResponse_<ContainerAllocator>& v)
  {
    s << indent << "traveledDistance: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.traveledDistance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVN_PLN_MESSAGE_MP_MOVE_DISTRESPONSE_H
