// Generated by gencpp from file mvn_pln/mp_obstacleResponse.msg
// DO NOT EDIT!


#ifndef MVN_PLN_MESSAGE_MP_OBSTACLERESPONSE_H
#define MVN_PLN_MESSAGE_MP_OBSTACLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace mvn_pln
{
template <class ContainerAllocator>
struct mp_obstacleResponse_
{
  typedef mp_obstacleResponse_<ContainerAllocator> Type;

  mp_obstacleResponse_()
    : found()  {
    }
  mp_obstacleResponse_(const ContainerAllocator& _alloc)
    : found(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _found_type;
  _found_type found;





  typedef boost::shared_ptr< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mp_obstacleResponse_

typedef ::mvn_pln::mp_obstacleResponse_<std::allocator<void> > mp_obstacleResponse;

typedef boost::shared_ptr< ::mvn_pln::mp_obstacleResponse > mp_obstacleResponsePtr;
typedef boost::shared_ptr< ::mvn_pln::mp_obstacleResponse const> mp_obstacleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator1> & lhs, const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.found == rhs.found;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator1> & lhs, const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvn_pln

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46ee5af4894e4648b96118490fdcd36d";
  }

  static const char* value(const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46ee5af4894e4648ULL;
  static const uint64_t static_value2 = 0xb96118490fdcd36dULL;
};

template<class ContainerAllocator>
struct DataType< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvn_pln/mp_obstacleResponse";
  }

  static const char* value(const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool found\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mp_obstacleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvn_pln::mp_obstacleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvn_pln::mp_obstacleResponse_<ContainerAllocator>& v)
  {
    s << indent << "found: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.found);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVN_PLN_MESSAGE_MP_OBSTACLERESPONSE_H
