// Generated by gencpp from file point_cloud_manager/GetRgbdRequest.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_MANAGER_MESSAGE_GETRGBDREQUEST_H
#define POINT_CLOUD_MANAGER_MESSAGE_GETRGBDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_cloud_manager
{
template <class ContainerAllocator>
struct GetRgbdRequest_
{
  typedef GetRgbdRequest_<ContainerAllocator> Type;

  GetRgbdRequest_()
    {
    }
  GetRgbdRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRgbdRequest_

typedef ::point_cloud_manager::GetRgbdRequest_<std::allocator<void> > GetRgbdRequest;

typedef boost::shared_ptr< ::point_cloud_manager::GetRgbdRequest > GetRgbdRequestPtr;
typedef boost::shared_ptr< ::point_cloud_manager::GetRgbdRequest const> GetRgbdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace point_cloud_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_manager/GetRgbdRequest";
  }

  static const char* value(const ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRgbdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::point_cloud_manager::GetRgbdRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_MANAGER_MESSAGE_GETRGBDREQUEST_H
