# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_msgs/OpenPoseRecognizeRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensor_msgs.msg
import std_msgs.msg

class OpenPoseRecognizeRequest(genpy.Message):
  _md5sum = "a290e9e25e4086fd604347d20967f215"
  _type = "vision_msgs/OpenPoseRecognizeRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """sensor_msgs/Image input_image

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of camera
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['input_image']
  _slot_types = ['sensor_msgs/Image']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       input_image

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpenPoseRecognizeRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.input_image is None:
        self.input_image = sensor_msgs.msg.Image()
    else:
      self.input_image = sensor_msgs.msg.Image()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.input_image.header.seq, _x.input_image.header.stamp.secs, _x.input_image.header.stamp.nsecs))
      _x = self.input_image.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.input_image.height, _x.input_image.width))
      _x = self.input_image.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.input_image.is_bigendian, _x.input_image.step))
      _x = self.input_image.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.input_image is None:
        self.input_image = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.input_image.header.seq, _x.input_image.header.stamp.secs, _x.input_image.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_image.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.input_image.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.input_image.height, _x.input_image.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_image.encoding = str[start:end].decode('utf-8')
      else:
        self.input_image.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.input_image.is_bigendian, _x.input_image.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.input_image.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.input_image.header.seq, _x.input_image.header.stamp.secs, _x.input_image.header.stamp.nsecs))
      _x = self.input_image.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.input_image.height, _x.input_image.width))
      _x = self.input_image.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.input_image.is_bigendian, _x.input_image.step))
      _x = self.input_image.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.input_image is None:
        self.input_image = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.input_image.header.seq, _x.input_image.header.stamp.secs, _x.input_image.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_image.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.input_image.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.input_image.height, _x.input_image.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.input_image.encoding = str[start:end].decode('utf-8')
      else:
        self.input_image.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.input_image.is_bigendian, _x.input_image.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.input_image.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_msgs/OpenPoseRecognizeResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import vision_msgs.msg

class OpenPoseRecognizeResponse(genpy.Message):
  _md5sum = "948e770d3707769324b3f1f72c6c76bf"
  _type = "vision_msgs/OpenPoseRecognizeResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """vision_msgs/OpenPoseRecognition[] recognitions


================================================================================
MSG: vision_msgs/OpenPoseRecognition
vision_msgs/OpenPoseKeyPoint[] keyPoints

================================================================================
MSG: vision_msgs/OpenPoseKeyPoint
int16 x
int16 y
float32 score
"""
  __slots__ = ['recognitions']
  _slot_types = ['vision_msgs/OpenPoseRecognition[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       recognitions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpenPoseRecognizeResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.recognitions is None:
        self.recognitions = []
    else:
      self.recognitions = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.recognitions)
      buff.write(_struct_I.pack(length))
      for val1 in self.recognitions:
        length = len(val1.keyPoints)
        buff.write(_struct_I.pack(length))
        for val2 in val1.keyPoints:
          _x = val2
          buff.write(_get_struct_2hf().pack(_x.x, _x.y, _x.score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.recognitions is None:
        self.recognitions = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.recognitions = []
      for i in range(0, length):
        val1 = vision_msgs.msg.OpenPoseRecognition()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.keyPoints = []
        for i in range(0, length):
          val2 = vision_msgs.msg.OpenPoseKeyPoint()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y, _x.score,) = _get_struct_2hf().unpack(str[start:end])
          val1.keyPoints.append(val2)
        self.recognitions.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.recognitions)
      buff.write(_struct_I.pack(length))
      for val1 in self.recognitions:
        length = len(val1.keyPoints)
        buff.write(_struct_I.pack(length))
        for val2 in val1.keyPoints:
          _x = val2
          buff.write(_get_struct_2hf().pack(_x.x, _x.y, _x.score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.recognitions is None:
        self.recognitions = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.recognitions = []
      for i in range(0, length):
        val1 = vision_msgs.msg.OpenPoseRecognition()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.keyPoints = []
        for i in range(0, length):
          val2 = vision_msgs.msg.OpenPoseKeyPoint()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y, _x.score,) = _get_struct_2hf().unpack(str[start:end])
          val1.keyPoints.append(val2)
        self.recognitions.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hf = None
def _get_struct_2hf():
    global _struct_2hf
    if _struct_2hf is None:
        _struct_2hf = struct.Struct("<2hf")
    return _struct_2hf
class OpenPoseRecognize(object):
  _type          = 'vision_msgs/OpenPoseRecognize'
  _md5sum = 'bc6fe00995db36c68d2577234a53f272'
  _request_class  = OpenPoseRecognizeRequest
  _response_class = OpenPoseRecognizeResponse
