# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_msgs/OpenPoseRecognitions.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import vision_msgs.msg

class OpenPoseRecognitions(genpy.Message):
  _md5sum = "a8a2d008e22b8c1b6e953e23aebdd53b"
  _type = "vision_msgs/OpenPoseRecognitions"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
vision_msgs/OpenPoseRecognition[] recognitions

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: vision_msgs/OpenPoseRecognition
vision_msgs/OpenPoseKeyPoint[] keyPoints

================================================================================
MSG: vision_msgs/OpenPoseKeyPoint
int16 x
int16 y
float32 score
"""
  __slots__ = ['header','recognitions']
  _slot_types = ['std_msgs/Header','vision_msgs/OpenPoseRecognition[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,recognitions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpenPoseRecognitions, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.recognitions is None:
        self.recognitions = []
    else:
      self.header = std_msgs.msg.Header()
      self.recognitions = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.recognitions)
      buff.write(_struct_I.pack(length))
      for val1 in self.recognitions:
        length = len(val1.keyPoints)
        buff.write(_struct_I.pack(length))
        for val2 in val1.keyPoints:
          _x = val2
          buff.write(_get_struct_2hf().pack(_x.x, _x.y, _x.score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.recognitions is None:
        self.recognitions = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.recognitions = []
      for i in range(0, length):
        val1 = vision_msgs.msg.OpenPoseRecognition()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.keyPoints = []
        for i in range(0, length):
          val2 = vision_msgs.msg.OpenPoseKeyPoint()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y, _x.score,) = _get_struct_2hf().unpack(str[start:end])
          val1.keyPoints.append(val2)
        self.recognitions.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.recognitions)
      buff.write(_struct_I.pack(length))
      for val1 in self.recognitions:
        length = len(val1.keyPoints)
        buff.write(_struct_I.pack(length))
        for val2 in val1.keyPoints:
          _x = val2
          buff.write(_get_struct_2hf().pack(_x.x, _x.y, _x.score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.recognitions is None:
        self.recognitions = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.recognitions = []
      for i in range(0, length):
        val1 = vision_msgs.msg.OpenPoseRecognition()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.keyPoints = []
        for i in range(0, length):
          val2 = vision_msgs.msg.OpenPoseKeyPoint()
          _x = val2
          start = end
          end += 8
          (_x.x, _x.y, _x.score,) = _get_struct_2hf().unpack(str[start:end])
          val1.keyPoints.append(val2)
        self.recognitions.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hf = None
def _get_struct_2hf():
    global _struct_2hf
    if _struct_2hf is None:
        _struct_2hf = struct.Struct("<2hf")
    return _struct_2hf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
