// Generated by gencpp from file knowledge_msgs/ask_store_nameRequest.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_ASK_STORE_NAMEREQUEST_H
#define KNOWLEDGE_MSGS_MESSAGE_ASK_STORE_NAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct ask_store_nameRequest_
{
  typedef ask_store_nameRequest_<ContainerAllocator> Type;

  ask_store_nameRequest_()
    : attempt_timeout(0)
    , repeat_timeout(0)
    , max_attempts(0)  {
    }
  ask_store_nameRequest_(const ContainerAllocator& _alloc)
    : attempt_timeout(0)
    , repeat_timeout(0)
    , max_attempts(0)  {
  (void)_alloc;
    }



   typedef int32_t _attempt_timeout_type;
  _attempt_timeout_type attempt_timeout;

   typedef int32_t _repeat_timeout_type;
  _repeat_timeout_type repeat_timeout;

   typedef int32_t _max_attempts_type;
  _max_attempts_type max_attempts;





  typedef boost::shared_ptr< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ask_store_nameRequest_

typedef ::knowledge_msgs::ask_store_nameRequest_<std::allocator<void> > ask_store_nameRequest;

typedef boost::shared_ptr< ::knowledge_msgs::ask_store_nameRequest > ask_store_nameRequestPtr;
typedef boost::shared_ptr< ::knowledge_msgs::ask_store_nameRequest const> ask_store_nameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator1> & lhs, const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.attempt_timeout == rhs.attempt_timeout &&
    lhs.repeat_timeout == rhs.repeat_timeout &&
    lhs.max_attempts == rhs.max_attempts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator1> & lhs, const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2572b3fb9d176b75a92c814bb14b18b8";
  }

  static const char* value(const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2572b3fb9d176b75ULL;
  static const uint64_t static_value2 = 0xa92c814bb14b18b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/ask_store_nameRequest";
  }

  static const char* value(const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 attempt_timeout\n"
"int32 repeat_timeout\n"
"int32 max_attempts\n"
;
  }

  static const char* value(const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.attempt_timeout);
      stream.next(m.repeat_timeout);
      stream.next(m.max_attempts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ask_store_nameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::ask_store_nameRequest_<ContainerAllocator>& v)
  {
    s << indent << "attempt_timeout: ";
    Printer<int32_t>::stream(s, indent + "  ", v.attempt_timeout);
    s << indent << "repeat_timeout: ";
    Printer<int32_t>::stream(s, indent + "  ", v.repeat_timeout);
    s << indent << "max_attempts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_attempts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_ASK_STORE_NAMEREQUEST_H
