// Generated by gencpp from file knowledge_msgs/InitKDBRequest.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_INITKDBREQUEST_H
#define KNOWLEDGE_MSGS_MESSAGE_INITKDBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct InitKDBRequest_
{
  typedef InitKDBRequest_<ContainerAllocator> Type;

  InitKDBRequest_()
    : filePath()
    , run(false)  {
    }
  InitKDBRequest_(const ContainerAllocator& _alloc)
    : filePath(_alloc)
    , run(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filePath_type;
  _filePath_type filePath;

   typedef uint8_t _run_type;
  _run_type run;





  typedef boost::shared_ptr< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitKDBRequest_

typedef ::knowledge_msgs::InitKDBRequest_<std::allocator<void> > InitKDBRequest;

typedef boost::shared_ptr< ::knowledge_msgs::InitKDBRequest > InitKDBRequestPtr;
typedef boost::shared_ptr< ::knowledge_msgs::InitKDBRequest const> InitKDBRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator1> & lhs, const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filePath == rhs.filePath &&
    lhs.run == rhs.run;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator1> & lhs, const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d40ee22877bfab4f2e1de8cb2e7b970";
  }

  static const char* value(const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d40ee22877bfab4ULL;
  static const uint64_t static_value2 = 0xf2e1de8cb2e7b970ULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/InitKDBRequest";
  }

  static const char* value(const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filePath\n"
"bool run\n"
;
  }

  static const char* value(const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filePath);
      stream.next(m.run);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitKDBRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::InitKDBRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::InitKDBRequest_<ContainerAllocator>& v)
  {
    s << indent << "filePath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filePath);
    s << indent << "run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_INITKDBREQUEST_H
