// Generated by gencpp from file knowledge_msgs/MapKnownLocation.msg
// DO NOT EDIT!


#ifndef KNOWLEDGE_MSGS_MESSAGE_MAPKNOWNLOCATION_H
#define KNOWLEDGE_MSGS_MESSAGE_MAPKNOWNLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace knowledge_msgs
{
template <class ContainerAllocator>
struct MapKnownLocation_
{
  typedef MapKnownLocation_<ContainerAllocator> Type;

  MapKnownLocation_()
    : name()
    , value()  {
    }
  MapKnownLocation_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> const> ConstPtr;

}; // struct MapKnownLocation_

typedef ::knowledge_msgs::MapKnownLocation_<std::allocator<void> > MapKnownLocation;

typedef boost::shared_ptr< ::knowledge_msgs::MapKnownLocation > MapKnownLocationPtr;
typedef boost::shared_ptr< ::knowledge_msgs::MapKnownLocation const> MapKnownLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator1> & lhs, const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator1> & lhs, const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace knowledge_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b31cd087b52c8acca2d7bf6ae29aeab";
  }

  static const char* value(const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b31cd087b52c8acULL;
  static const uint64_t static_value2 = 0xca2d7bf6ae29aeabULL;
};

template<class ContainerAllocator>
struct DataType< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowledge_msgs/MapKnownLocation";
  }

  static const char* value(const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float32[] value\n"
;
  }

  static const char* value(const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapKnownLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowledge_msgs::MapKnownLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowledge_msgs::MapKnownLocation_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWLEDGE_MSGS_MESSAGE_MAPKNOWNLOCATION_H
